# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"trace_log": "01_convert_time_log.ipynb",
         "format_value": "01_convert_time_log.ipynb",
         "strip_extra_EnmacClientTime_elements": "01_convert_time_log.ipynb",
         "unix_time_millis": "01_convert_time_log.ipynb",
         "parse_dt": "01_convert_time_log.ipynb",
         "parse_dt_to_millis": "01_convert_time_log.ipynb",
         "parse_timing_log": "01_convert_time_log.ipynb"}

modules = ["convert_time_log.py"]

doc_url = "https://3ideas.github.io/cronos/"

git_url = "https://github.com/3ideas/cronos/tree/master/"

def custom_doc_links(name): return None
